#!/usr/bin/env bash

DATADIR=../MMCFBlock/data

for what in ${DATADIR}/Canad/*.dat; do

  printf "[$what s]: "

  ./LDS_MMCF_test $what s

  retVal=$?
  if [ $retVal -ne 0 ]; then
    exit 1
  fi

done
