#!/usr/bin/env bash

what=31
#what=1
#iter=10

#for size in 2 10 50 100
for size in 2 10 50; do
  for dens in 3 1.1; do
    for (( seed = 0 ; seed < 20 ; seed++ )); do

      if [ -z "$iter" ]; then
        printf "[$seed $what $size $dens]: "
      else
        printf "[$seed $what $size $dens $iter]: "
      fi

      ./PolyhedralFunction_test $seed $what $size $dens $iter

      retVal=$?
      if [ $retVal -ne 0 ]; then
        exit 1
      fi

    done
  done
done
