#!/usr/bin/env bash

seed=264
wchg=127
n_repeat=50

for N in 100 500 3000; do

  for delta in 0.005 0.05 0.3 0.6; do

    for nW in 0 0.2 0.7 1; do

      for nP in 0 0.2 0.7 1; do

        for nI in 0 0.2 0.8 1; do

          for nM in 0 0.2 0.7 1; do

            printf "[$seed $wchg $N $n_repeat $delta $nW $nP $nI $nM]: "

            ./BinaryKnapsackBlock_test $seed $wchg $N $n_repeat $delta $nW $nP $nI $nM

            retVal=$?
            if [ $retVal -ne 0 ]; then
              exit 1
            fi

          done
        done
      done
    done
  done
done
