##############################################################################
################################# makefile ###################################
##############################################################################
#                                                                            #
#   makefile of MMCFClass                                                    #
#                                                                            #
#   Input:  $(MMFDIR) = the directory where the source is                    #
#                                                                            #
#   Output: $(MMFH)   = the .h files to include                              #
#           $(MMFINC) = the -I$(include directories)                         #
#                                                                            #
#                              Antonio Frangioni                             #
#                         Dipartimento di Informatica                        #
#                             Universita' di Pisa                            #
#                                                                            #
##############################################################################

MMFINC = -I$(MMFDIR) 
MMFH = $(MMFDIR)/MMCFClas.h

############################ End of makefile #################################
