#!/usr/bin/env bash

what=3
#iter=0

for size in 2 10 50 100 1000; do
  for (( seed = 0 ; seed < 20 ; seed++ )); do

    if [ -z "$iter" ]; then
      printf "[$seed $what $size]: "
    else
      printf "[$seed $what $size $iter]: "
    fi

    ./BoxSolver_test $seed $what $size $iter

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done
